### ISSUE TITLE
BUG: EXP stage lua don't take a efect

### ISSUE THREAD

**Issue by LuisDominguez** [opentibiabr/otservbr-global-archived#2329] opened 2021-01-30 00:10 UTC
#### Describe the bug
> When i change the values of stages.lua

```
experienceStages = {
	{
		minlevel = 1,
		maxlevel = 8,
		multiplier = 200
	}, {
		minlevel = 9,
		maxlevel = 20,
		multiplier = 100
	}, {
		minlevel = 21,
		maxlevel = 50,
		multiplier = 300
	}, {
		minlevel = 51,
		maxlevel = 100,
		multiplier = 300
	}, {
		minlevel = 101,
		multiplier = 300
	}
}
```

this doesn't work, the exp still 1x, on my config lua a still values:

```
rateExp = 1
rateSkill = 50
rateLoot = 3
rateMagic = 25
rateSpawn = 1a
```
yesterday, i download the last development version and i don't change any files

**Comment by shakkurcwb** [comment] 2021-02-14 01:33
I have the same issue. Even setting the config `rateExp` to 2 does not take effect. Some kind of caching?

**Comment by wizardlink** [comment] 2021-02-14 01:44
> I have the same issue. Even setting the config `rateExp` to 2 does not take effect. Some kind of caching?

`rateExp` is only used if there is no stage set for the player's current level. You technically can change the stages on the fly, but, it depends what LUA engine you are using. As a rule of thumb, just restart it.

As for whether this is a problem or not... I couldn't reproduce the issue in my server and locally, both correctly change the rates.

**Comment by shakkurcwb** [comment] 2021-02-14 02:13
reverting #[b30feb3 ](https://github.com/opentibiabr/otservbr-global/commit/b30feb3b93891bbf31aecb48bc871ddc98803692)solved most of the issues to me, including issues with changing outfit.

**Comment by shakkurcwb** [comment] 2021-02-14 22:07
i can repeat my comment here, even if admin does not like it.
reverting #[b30feb3](https://github.com/opentibiabr/otservbr-global/commit/b30feb3b93891bbf31aecb48bc871ddc98803692) solve the issue.
Now that the same author committed a fix, does not imply my comment should be removed.
If you need the issue history (without deleted comments), just let me know. ;)

**Comment by wizardlink** [comment] 2021-02-14 22:34
> i can repeat my comment here, even if admin does not like it.
> reverting #[b30feb3](https://github.com/opentibiabr/otservbr-global/commit/b30feb3b93891bbf31aecb48bc871ddc98803692) solve the issue.
> Now that the same author committed a fix, does not imply my comment should be removed.
> If you need the issue history (without deleted comments), just let me know. ;)

It was publicly stated in their Discord about the faulty commit, no clue what's up with the deleted comment. Perhaps automation?

**Comment by shakkurcwb** [comment] 2021-02-14 22:38
I'm not on Discord since I was excluded due to my post noticing that the support chat was used for talk not support. Not my fault either.

**Comment by dudantas** [comment] 2021-02-14 23:04
![image](https://user-images.githubusercontent.com/8551443/107891841-e30e1980-6eff-11eb-8bdb-d0ecf829fd06.png)
Reading is good ... Config.lua rates are only fallback

**Closed as completed by dudantas** 2021-02-14 23:04 UTC
Labels: Type: Bug

**Comment by dudantas** [comment] 2021-02-14 23:06
> I'm not on Discord since I was excluded due to my post noticing that the support chat was used for talk not support. Not my fault either.

Never seen you on otservbr - global discord group

https://discordapp.com/invite/3NxYnyV

**Comment by majestyotbr** [comment] 2021-02-14 23:11
> I'm not on Discord since I was excluded due to my post noticing that the support chat was used for talk not support. Not my fault either.

You was banned from the otbr community discord (https://discordapp.com/invite/q3e56R2)  for lack of respect. You can come back there if you respect the rules.
The OTServBR-Global project have his own discord:
https://discordapp.com/invite/3NxYnyV

**Comment by shakkurcwb** [comment] 2021-02-14 23:15
Yeah, you can spread anything you would like to. Good luck with that.

**Comment by shakkurcwb** [comment] 2021-02-14 23:17
Also nice that you're solving an issue that was created before the faulty commit. Good interpretation.
