### ISSUE TITLE
FEATURE: Cult of Barklesss - Ab'Dendriel / Bug Mechanic Boss

### ISSUE THREAD

**Issue by LeoTKBR** [opentibiabr/otservbr-global-archived#2168] opened 2020-12-27 00:28 UTC
Killing the first laiden boss does not create the next ravennous hunger boss
![Sem títul32o](https://user-images.githubusercontent.com/41605307/103161490-3f3aa400-47c1-11eb-9f29-9d792c2938a8.png)

**Comment by travisani** [comment] 2020-12-29 20:51
Confirmed.

**Comment by oualid6496** [comment] 2021-01-17 16:26
It's because the creatureevents don't get registered, I once made a issue about it but I believe someone closed it without solving it. Because there already is a issue about revising the whole quest. A temporary fix would be adding the spawnboss and leidenheal creatureevents directly to leiden's monster file but you will find a lot of other bugs in this quest because none of the creatureevents register for any boss.

**Comment by marcosvf132** [comment] 2021-02-14 03:59
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726

**Closed as completed by marcosvf132** 2021-02-14 03:59 UTC
Labels: Type: Enhancement
