### ISSUE TITLE
Monster still fast, quickloot problems.

### ISSUE THREAD

**Issue by Alucard987** [opentibiabr/otservbr-global-archived#1137] opened 2020-05-04 06:16 UTC
sorry for write again.
using the last build. and i still ultra-fast monsters? can help me to solve it?
thanks!!!
another problem.
recent corpses can'r move them. i only try in rats xD
last problem.
quickloot isn't work, console say this in the server start

> [Warning - Items::parseItemNode] Unknown key value: quicklootcategory

in-game says the following

>  Lua Script Error: [Modules Interface]
> 
> data/modules/scripts/quickloot/quickloot.lua:onRecvbyte
> data/modules/scripts/quickloot/quickloot.lua:131: attempt to call method 'canOpenCorpse' (a nil value)
> stack traceback:
>         [C]: in function 'canOpenCorpse'
>         data/modules/scripts/quickloot/quickloot.lua:131: in function <data/modules/scripts/quickloot/quickloot.lua:74>
> 

the last error says the following. I do not know what it is.

> Lua Script Error: [Event Interface]
> data/events/scripts/player.lua:Player@onGainExperience
> data/global.lua:133: bad argument #1 to 'ipairs' (table expected, got nil)
> stack traceback:
>         [C]: at 0x7ff74807a6d0
>         [C]: in function 'ipairs'
>         data/global.lua:133: in function 'getRateFromTable'
>         data/events/scripts/player.lua:764: in function <data/events/scripts/player.lua:751>
> 
> Lua Script Error: [Event Interface]
> data/events/scripts/monster.lua:Monster@onDropLoot
> data/events/scripts/monster.lua:31: attempt to call method 'updateKillTracker' (a nil value)
> stack traceback:
>         [C]: in function 'updateKillTracker'
>         data/events/scripts/monster.lua:31: in function <data/events/scripts/monster.lua:1>
> 
regards!

**Comment by dudantas** [comment] 2020-05-04 15:02
Hello, sorry for the delay in replying. The issue was closed for being unconfirmed. I did the tests and couldn't reproduce.
Make sure that:
You are using the updated datapack, source and database.
Just in case, download everything from 0 and test again.

If you are still able to reproduce the problem. Explain exactly how to reproduce, step by step, what was done. Thus, we can investigate, the information you gave is vague and so you can't do much.

I'm closing for lack of information and for not being able to reproduce, if you have more information, if you can find out the cause, even if it's not a problem with the repository, report here, so you can help other people.
Thank you for understanding.

**Comment by gpedro** [comment] 2020-05-04 15:30
quickloot and onGainExperience confirmed.

**Comment by Alucard987** [comment] 2020-05-04 18:41
new problem. new players apear in rookgard without starting items.

**Comment by dudantas** [comment] 2020-05-04 18:43
> new problem. new players apear in rookgard without starting items.

Yes, this is normal. Access to rookgaard will be the same as global, only through dawnport.
We are already developing this here https://github.com/opentibiabr/otservbr-global/pull/1134

If you can make a new issue talking about this rook, we link to the Pull Request and as soon as it is ready, we will let you know.

**Comment by winimattos1** [comment] 2020-07-20 04:55
About Quicklooting:

When i'm over dead creature and click shift+righ button i can't loot dead corpse.
Returns attached image.
![QuickLoot](https://user-images.githubusercontent.com/68520053/87900898-fde0e400-ca2b-11ea-9b9b-cbc67508d28b.JPG)

**Comment by gpedro** [comment] 2020-07-20 05:56
@winimattos1 can you try this PR? https://github.com/opentibiabr/otservbr-global/pull/1400

**Comment by winimattos1** [comment] 2020-07-20 19:46
> @winimattos1 can you try this PR? #1400

Same Problem

**Comment by majestyotbr** [comment] 2020-07-20 21:41
You did it correctly? In PR 1400 the file quickloot.lua does not exist anymore.

**Comment by winimattos1** [comment] 2020-07-21 12:30
> You did it correctly? In PR 1400 the file quickloot.lua does not exist anymore.

A não ser que eu esteja fazendo algo errado, continua igual.
Baixei o projeto de novo, recompilei e continuo com o mesmo problema ao lootear com shift + right click.
Quando o corpo morto está com algo vivo em cima, ele não realiza a ação de lootear, gerando o erro que mandei na print anterior.

-----

Unless I'm doing something wrong, it's still the same.
I downloaded the project again, recompiled and I still have the same problem when loot with shift + right click.
When the dead body has something alive on top, it does not perform the action of loot, generating the error that I sent in the previous print.

**Comment by dudantas** [comment] 2020-07-21 12:32
@winimattos1 nem tem como gerar esse mesmo erro no quickloot em cpp pois ele não tem essa função. Você deve ter compilado errado.

**Comment by dudantas** [comment] 2020-07-21 12:34
Baixe aqui: https://github.com/opentibiabr/otservbr-global/tree/quickloot-cpp

E teste novamente, por gentileza.

Lembra de usar toda a pack que você baixar e recompilar a source que vier dentro.

**Comment by winimattos1** [comment] 2020-07-21 12:35
@dudantas vou verificar esse link e já passo um retorno.

Não tenho muita proximidade com o git, então eu devo estar fazendo besteira, provavelmente.

**Comment by winimattos1** [comment] 2020-07-21 12:36
Não tenho muita proximidade com o git, então eu devo estar fazendo besteira, provavelmente.

**Comment by winimattos1** [comment] 2020-07-21 13:20
@dudantas realmente eu tava fazendo besteira. Agora deu certo. Valeu o apoio

**Comment by dudantas** [comment] 2020-07-21 13:20
Entendo. Mas, faz como falei. Baixa do link que mandei, compila a source que baixar e joga dentro da própria pasta que fez download. Eu não cheguei a testar se tá com esse bug, mas eu acho que não tá.

**Comment by winimattos1** [comment] 2020-07-21 13:24
> Entendo. Mas, faz como falei. Baixa do link que mandei, compila a source que baixar e joga dentro da própria pasta que fez download. Eu não cheguei a testar se tá com esse bug, mas eu acho que não tá.

Tá correto, só demorei pq estou trabalhando em paralelo e precisei reinstalar o Myacc porque eu já tinha mexido nas contas, mas tá funcionando corretamente a principio. O único problema que tenho agora é referente a Store que quando eu clico fecha, não sei se há alguma topico sobre isso, mas qualquer modo não vou conseguir conferir agora.

**Closed as completed** 2020-08-25 00:50 UTC
Labels: Type: Bug, code
