### ISSUE TITLE
FEATURE: Cult of Life - Darashia / Bug Mechanic Boss

### ISSUE THREAD

**Issue by LeoTKBR** [opentibiabr/otservbr-global-archived#2167] opened 2020-12-27 00:21 UTC
There is simply no mechanics in this boss it does not disappear and there are no other monsters to kill
![Sem tídsadastulo](https://user-images.githubusercontent.com/41605307/103161421-5cbb3e00-47c0-11eb-8558-ce3f0e4ef2bb.png)

**Comment by travisani** [comment] 2020-12-29 20:51
Confirmed.

**Comment by oualid6496** [comment] 2021-01-17 16:27
It's because the creatureevents don't get registered, I once made a issue about it but I believe someone closed it without solving it. Because there already is a issue about revising the whole quest. A temporary fix would be adding the creatureevents directly to the monster files. I however don't know how to permenantly fix it.

**Comment by marcosvf132** [comment] 2021-02-14 03:59
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726

**Closed as completed by marcosvf132** 2021-02-14 03:59 UTC
Labels: Type: Enhancement
