### ISSUE TITLE
BUG: Server crash when remove monster from charm

### ISSUE THREAD

**Issue by lichak232** [opentibiabr/otservbr-global-archived#2655] opened 2021-06-28 19:53 UTC
#### Describe the bug
> While removing monster from charm

#### How to Reproduce?
> It's hard to repeat

> Give us all details to reproduce the behavior:
> Remove monster from charm
> It's hard to repeat

#### Logs or errors
> https://pastebin.com/Mz6qHPA5

#### Expected behavior
> Server crash

#### Screenshots
> ![image](https://user-images.githubusercontent.com/78379131/123695755-3c496a80-d85b-11eb-9693-62cddf242574.png)

#### Environment
- OS (e.g. Debian 10.9 Buster): 
- OTServ Version (e.g. latest): 
- Tibia Version (e.g. 12.64): 

#### Additional context
> In secure i have added quick loot all corpses

**Comment by yatozin** [comment] 2021-06-28 23:16
have been having the same issue

**Comment by beats-dh** [comment] 2021-06-29 02:06
What? I did not understand, could you explain better?

**Comment by lichak232** [comment] 2021-06-29 03:35
What do you need in more info?

**Comment by yatozin** [comment] 2021-06-29 04:15
> What? I did not understand, could you explain better?

![image](https://user-images.githubusercontent.com/55179288/123736381-2092a280-d8f5-11eb-953e-09310359b2c0.png)
![image](https://user-images.githubusercontent.com/55179288/123736439-3607cc80-d8f5-11eb-8b67-d99faf6aa971.png)

**Comment by xThauma** [comment] 2021-06-29 08:46
Can't reproduce it, even tried it on 100 ms attack speed attacking monster multiple times, adding and removing charms.

Did you make any custom changes?

**Comment by lichak232** [comment] 2021-06-29 12:41
> Can't reproduce it, even tried it on 100 ms attack speed attacking monster multiple times, adding and removing charms.
> 
> Did you make any custom changes?

only this #2237

**Comment by xThauma** [comment] 2021-06-29 12:45
> > Can't reproduce it, even tried it on 100 ms attack speed attacking monster multiple times, adding and removing charms.
> > Did you make any custom changes?
> 
> only this #2237

I have tried it too and still cannot reproduce. What monster and what charm are you trying?

**Comment by lichak232** [comment] 2021-06-29 12:48
I tried many times too on my test server and nothing. My friend login on test server and he do this one time and he failed more.
I have information about it from one of my players. No matter what charms and monster.


Player: "so when i cleared "zap" it crashed once, then after the first crashed i cleared zap again, it didnt  crash
but then i cleared divine wrath and the server crashed again
its kinda crashed once per charm, also dont know it the position of my char or "infight" matters to it"
Friend on test server: in house Draken Warmaster from dodge charm.

**Comment by Costallat** [comment] 2021-06-29 14:06
Sorry but you are using a customized code, you merged an unfinished PR so you are on your own to solve that, like others have answered here, the problem doesn't happens on the development branch.

**Closed as completed by Costallat** 2021-06-29 14:06 UTC
Labels: Type: Bug

**Comment by lichak232** [comment] 2021-06-29 14:42
@Costallat okey, so i compile clear src and try again.

**Comment by Schiffers** [comment] 2021-08-02 18:19
Any news ?
Cant reproduce in my ot...
Just asking, Just because have some rumors about this crash on the Otservbr base

**Comment by hyagosrs** [comment] 2021-09-15 20:29
I have same issue.
