### ISSUE TITLE
Remove Dawnport

### ISSUE THREAD

**Issue by matheuspergher** [opentibiabr/otservbr-global-archived#1290] opened 2020-06-02 07:09 UTC
Hey guys. 

I just wanna know if its possible to remove Dawnport and put the characters straight on Thais temple
and receiving the initial items?

Thank you.

**Comment by dudantas** [comment] 2020-06-02 07:23
You will disable the rook sample on your website.
Then you will activate the choice of towns (at your discretion, usually in config.php) and add the items you want to start in the samples (sorcerer, druid, paladin and knight)

**Comment by matheuspergher** [comment] 2020-06-02 07:55
Sorry about this question, but how can I remove the samples? Removing the rook sample from the table?

Thx mate

**Comment by dudantas** [comment] 2020-06-02 08:04
Can not. The website uses the samples to create the characters. If you remove, you will not be able to create char. (with the exception of znote which has everything stored on the website itself)

**Comment by matheuspergher** [comment] 2020-06-02 08:07
Hmmm, so How can I do that?

**Comment by dudantas** [comment] 2020-06-02 08:10
What do you want to remove them for?

**Comment by dudantas** [comment] 2020-06-02 08:10
Sorry, when I said remove, I meant in the website settings (not from database). Which website do you use?

**Comment by matheuspergher** [comment] 2020-06-02 08:11
I understood how to put the items on new characters, but how can I change where the players will be born?

**Comment by matheuspergher** [comment] 2020-06-02 08:12
> Sorry, when I said remove, I meant in the website settings (not from database). Which website do you use?

I'm using Gesior2012.

**Comment by Vrxey31** [comment] 2020-06-02 08:31
I have the same problem. Before update i had sample in database but if i changed town_id and POS X/Y/Z didn't work. New characters spawned in Rookgaard without items but with vocation

**Comment by matheuspergher** [comment] 2020-06-02 08:33
> I have the same problem. Before update i had sample in database but if i changed town_id and POS X/Y/Z didn't work. New characters spawned in Rookgaard without items but with vocation

Yeah, that's what I'm trying to change... I don't wanna the players born in Rookgard or Dawnport, but in Thais or horewer..

**Comment by dudantas** [comment] 2020-06-02 08:46
The problem is your map, probably the towns ids are different from ours.

**Comment by dudantas** [comment] 2020-06-02 08:46
You want to disable dawnport / rookgaard and send it straight to main, correct?

**Comment by matheuspergher** [comment] 2020-06-02 08:47
> You want to disable dawnport / rookgaard and send it straight to main, correct?

Yeah, please o/

**Comment by dudantas** [comment] 2020-06-02 08:50
Go here:
https://github.com/gesior/Gesior2012/blob/268f477369c5c4a8ba88084224142941cba15654/config/config.php#L24
Place the town you want the player to be born in and it will be done. (remember to activate the samples, as shown in the line above)

```lua
$config['site']['newchar_vocations'] = array(1 => 'Sorcerer Sample', 2 => 'Druid Sample', 3 => 'Paladin Sample', 4 => 'Knight Sample');
$config['site']['newchar_towns'] = array(2);
```

**Comment by Vrxey31** [comment] 2020-06-02 08:52
> Go here:
> https://github.com/gesior/Gesior2012/blob/268f477369c5c4a8ba88084224142941cba15654/config/config.php#L24
> Place the town you want the player to be born in and it will be done. (remember to activate the samples, as shown in the line above)
> 
> ```lua
> $config['site']['newchar_vocations'] = array(1 => 'Sorcerer Sample', 2 => 'Druid Sample', 3 => 'Paladin Sample', 4 => 'Knight Sample');
> $config['site']['newchar_towns'] = array(2);
> ```

How to change this in MyACC?

**Comment by matheuspergher** [comment] 2020-06-02 08:55
> Go here:
> https://github.com/gesior/Gesior2012/blob/268f477369c5c4a8ba88084224142941cba15654/config/config.php#L24
> Place the town you want the player to be born in and it will be done. (remember to activate the samples, as shown in the line above)
> 
> ```lua
> $config['site']['newchar_vocations'] = array(1 => 'Sorcerer Sample', 2 => 'Druid Sample', 3 => 'Paladin Sample', 4 => 'Knight Sample');
> $config['site']['newchar_towns'] = array(2);
> ```

Mine is exactly like that:

# Create Character Options
$config['site']['newchar_vocations'] = array(1 => 'Sorcerer Sample', 2 => 'Druid Sample', 3 => 'Paladin Sample', 4 => 'Knight Sample');
$config['site']['newchar_towns'] = array(2);
$config['site']['max_players_per_account'] = 7;

**Comment by dudantas** [comment] 2020-06-02 08:56
> > Go here:
> > https://github.com/gesior/Gesior2012/blob/268f477369c5c4a8ba88084224142941cba15654/config/config.php#L24
> > Place the town you want the player to be born in and it will be done. (remember to activate the samples, as shown in the line above)
> > ```lua
> > $config['site']['newchar_vocations'] = array(1 => 'Sorcerer Sample', 2 => 'Druid Sample', 3 => 'Paladin Sample', 4 => 'Knight Sample');
> > $config['site']['newchar_towns'] = array(2);
> > ```
> 
> How to change this in MyACC?

Here: 
https://github.com/slawkens/myaac/blob/1087aefe0ad187630caf78326f67a22512caeb60/config.php#L156
And here:
https://github.com/slawkens/myaac/blob/1087aefe0ad187630caf78326f67a22512caeb60/config.php#L167

**Comment by dudantas** [comment] 2020-06-02 08:57
> array(2);

Change "array(2);" for the number of town (That you want the chars to start)
Example, thais is "8"

**Comment by matheuspergher** [comment] 2020-06-02 09:02
> > array(2);
> 
> Change "array(2);" for the number of town (That you want the chars to start)
> Example, thais is "8"

Sensational mate. Thank you so much.

**Comment by dudantas** [comment] 2020-06-02 09:05
@Vrxey31 solved for you? 

You can see the list of towns here:
https://github.com/opentibiabr/otservbr-global/blob/develop/data/lib/tables/town.lua

**Comment by dudantas** [comment] 2020-06-02 09:05
Let me know if it's resolved, so I'll close the issue.

**Comment by matheuspergher** [comment] 2020-06-02 09:06
> Let me know if it's resolved, so I'll close the issue.

Yeah, for me, it's solved. Thank you for your help

**Closed as completed** 2020-06-02 10:01 UTC
Labels: Type: Question
