### ISSUE TITLE
FEATURE: Bug Cult Of Carlin / Boss Room

### ISSUE THREAD

**Issue by LeoTKBR** [opentibiabr/otservbr-global-archived#2165] opened 2020-12-26 23:51 UTC
after killing all the monsters in the room the boss is not created
![Sem títul32o](https://user-images.githubusercontent.com/41605307/103161135-0e0ba500-47bc-11eb-89a3-371ea6eb1ba0.png)

**Comment by travisani** [comment] 2020-12-29 20:51
Confirmed.

**Comment by oualid6496** [comment] 2021-01-17 16:27
It's because the creatureevents don't get registered, I once made a issue about it but I believe someone closed it without solving it. Because there already is a issue about revising the whole quest. A temporary fix would be adding the creatureevents directly to the monster files. I however don't know how to permenantly fix it.

**Comment by marcosvf132** [comment] 2021-02-14 03:59
Due to a huge amount of issues, we are moving all bugs related to quest to one single ISSUE, for future issues related to the quest, please consider reporting it on that specific ISSUE, thanks.
 - Ref: #726

**Closed as completed by marcosvf132** 2021-02-14 03:59 UTC
Labels: Type: Enhancement
