### ISSUE TITLE
OTClient bug

### ISSUE THREAD

**Issue by Briluxxx** [opentibiabr/otservbr-global-archived#1701] opened 2020-08-27 21:11 UTC
when trying to use OTClient this happens...
https://imgur.com/iNLZslf

it only happens with this version 12.40, in version 12.20 it works fine

I used the dat and spr of the client 10 that you update as well as others that I got and none works

I am using the most recent version and of the page I use ZnoteACC

**Comment by dudantas** [comment] 2020-08-27 21:15
This is because your otclient does not support 12.20+
It's like trying to log in to the 12.40 server using Tibia 12.20 client, it will debug
OTC does not debug, but you can look at the console that is full of errors ...

**Comment by dudantas** [comment] 2020-08-27 21:18
Well. Considering that the problem is in the OTC and not in the project, I will be closing.
Feel free to ask for support from those who provided the client

**Closed as completed by dudantas** 2020-08-27 21:18 UTC
