### ISSUE TITLE
FEATURE: Bug XP gain rate

### ISSUE THREAD

**Issue by amoxicilinaaa** [opentibiabr/otservbr-global-archived#2208] opened 2020-12-31 00:22 UTC
Ao alterar o valor do **Xp gain rate** em player.lua não altera em nada na experiência da criatura e conta premium não tem uma vantagem sobre a free accont na porcentagem da **Exp Gain rate** ela e alterada apenas quando mata a criataura e não quando logar no personagem.

Changing the value of the **XP gain rate** in player.lua does not change the creation experience at all and the premium account does not have an advantage over the free account in the percentage of the **Exp gain rate** and only changed when you kill the creature and not when you log into the character.

screens / Fotos:
```
	local expStage = getRateFromTable(experienceStages, self:getLevel(), configManager.getNumber(configKeys.RATE_EXP))
	exp = exp * expStage
	baseExp = rawExp * expStage
	if Game.getStorageValue(GlobalStorage.XpDisplayMode) > 0 then
		displayRate = expStage
	else
		displayRate = **1**

	end
```
![4s2wdl](https://user-images.githubusercontent.com/38027045/103387545-2b55b180-4ae3-11eb-9475-2dda7b3163d1.gif)
![4s2wm8](https://user-images.githubusercontent.com/38027045/103387573-46c0bc80-4ae3-11eb-81f6-351f05ab1594.gif)
![4s2yqq](https://user-images.githubusercontent.com/38027045/103387725-17f71600-4ae4-11eb-85d4-b61b47fb6bd2.gif)

**Comment by hyresu** [comment] 2020-12-31 06:48
XP gain rate doesn't influence on the xp gained, that's only a value for the client, change the rates of your server if you want more or less experience rate.

**Comment by amoxicilinaaa** [comment] 2020-12-31 12:26
and that in the global tibia the XP gain rate influences the creatures' experience that's why I reported

**Comment by hyresu** [comment] 2020-12-31 17:25
Yes, but what I mean is that the xp gain rate is just a number displayed on the client, you change it, but the total exp is stored in the "exp" variable, the XP Gain Rate can be set to 0 in a client or set to 10000, but if the variable "exp" is unaffected then the only change will be in the client, not in the exp received

**Comment by hyresu** [comment] 2021-01-04 16:21
Will close this as it's not a bug nor a enhancement

**Closed as completed by hyresu** 2021-01-04 16:21 UTC
Labels: Type: Enhancement
